// <auto-generated />
using System;
using FitApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitApp.Models.DailyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DailyReportCalories")
                        .HasColumnType("int");

                    b.Property<double?>("DailyReportCarbon")
                        .HasColumnType("float");

                    b.Property<DateTime>("DailyReportDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DailyReportFat")
                        .HasColumnType("float");

                    b.Property<double?>("DailyReportProtein")
                        .HasColumnType("float");

                    b.Property<double?>("DailyReportWater")
                        .HasColumnType("float");

                    b.Property<double>("DailyReportWeight")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyReports");
                });

            modelBuilder.Entity("FitApp.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealId"));

                    b.Property<int>("MealCalories")
                        .HasColumnType("int");

                    b.Property<int>("MealCarbon")
                        .HasColumnType("int");

                    b.Property<int>("MealFat")
                        .HasColumnType("int");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MealProtein")
                        .HasColumnType("int");

                    b.HasKey("MealId");

                    b.ToTable("MealReports");
                });

            modelBuilder.Entity("FitApp.Models.MealEntry", b =>
                {
                    b.Property<int>("MealEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealEntryId"));

                    b.Property<int>("DailyReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MealEntryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MealEntryQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.HasKey("MealEntryId");

                    b.HasIndex("DailyReportId");

                    b.HasIndex("MealId");

                    b.ToTable("MealEntries");
                });

            modelBuilder.Entity("FitApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("UserBmi")
                        .HasColumnType("int");

                    b.Property<int>("UserCurrentWeight")
                        .HasColumnType("int");

                    b.Property<DateTime>("UserDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitApp.Models.DailyReport", b =>
                {
                    b.HasOne("FitApp.Models.User", "User")
                        .WithMany("DailyReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitApp.Models.MealEntry", b =>
                {
                    b.HasOne("FitApp.Models.DailyReport", "DailyReport")
                        .WithMany("MealEntries")
                        .HasForeignKey("DailyReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitApp.Models.Meal", "Meal")
                        .WithMany("MealEntries")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyReport");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FitApp.Models.DailyReport", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("FitApp.Models.Meal", b =>
                {
                    b.Navigation("MealEntries");
                });

            modelBuilder.Entity("FitApp.Models.User", b =>
                {
                    b.Navigation("DailyReports");
                });
#pragma warning restore 612, 618
        }
    }
}
